import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
dynamic_title = true
padding = { x = 16, y = 3 }

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
